import { z } from "zod";

export const evidenceSchema = z.object({ id:z.string(), url:z.string().url(), text:z.string(), selector:z.string().optional(), pageId:z.string().optional() });
export const entitySchema = z.object({ id:z.string(), name:z.string(), type:z.enum(["Person","Organization","Product","Project","Service","Location","Technology","Article","Event","Concept","Other"]), description:z.string().optional(), evidenceIds:z.array(z.string()).default([]) });
export const relationshipSchema = z.object({ id:z.string(), subjectId:z.string(), predicate:z.enum(["created","built","works_at","offers","located_in","owns","developed","specializes_in","authored","manufactures","provides","part_of","related_to"]), objectId:z.string(), evidenceIds:z.array(z.string()).min(1), confidence:z.number().min(0).max(1) });
export const claimSchema = z.object({ id:z.string(), subject:z.string(), predicate:z.string(), object:z.string(), importance:z.number().min(0).max(1), evidenceIds:z.array(z.string()).min(1) });
export const pageSchema = z.object({ id:z.string(), url:z.string().url(), status:z.number().int(), title:z.string().default(""), description:z.string().default(""), canonicalUrl:z.string().url().nullable().default(null), headings:z.array(z.object({level:z.number().int().min(1).max(6),text:z.string()})).default([]), text:z.string().default(""), links:z.array(z.string().url()).default([]), jsonLd:z.array(z.unknown()).default([]), fingerprint:z.string(), contentType:z.string(), duplicateOf:z.string().nullable().default(null) });
export const crawlOutputSchema = z.object({ target:z.string().url(), startedAt:z.string(), completedAt:z.string(), robots:z.object({url:z.string().url(),allowed:z.boolean(),sitemaps:z.array(z.string().url()),status:z.number().nullable()}), pages:z.array(pageSchema), crawlEdges:z.array(z.object({from:z.string().url(),to:z.string().url()})), warnings:z.array(z.string()), limits:z.object({maxPages:z.number(),maxDepth:z.number(),maxBytes:z.number(),timeoutMs:z.number(),maxRedirects:z.number()}) });

export const siteAnalysisSchema = z.object({ primaryEntity:z.object({name:z.string(),type:z.string(),description:z.string()}), siteArchetype:z.string(), secondaryArchetypes:z.array(z.string()), purpose:z.array(z.string()), importantInformationClasses:z.array(z.string()), expectedUserQuestions:z.array(z.string()), confidence:z.object({overall:z.number().min(0).max(1),reasons:z.array(z.string())}), ambiguities:z.array(z.string()) });
export const semanticGraphSchema = z.object({ entities:z.array(entitySchema), relationships:z.array(relationshipSchema), claims:z.array(claimSchema) });
export const dimensionIdSchema = z.enum(["machine_accessibility","semantic_extraction","entity_clarity","relationship_preservation","claim_retrievability","structured_evidence","ai_search_discoverability"]);
export const contractSchema = z.object({ archetype:z.string(), dimensions:z.array(z.object({id:dimensionIdSchema,reason:z.string()})), unsupportedObservations:z.array(z.string()).default([]) });
export const survivalSchema = z.object({ claimId:z.string(), stages:z.array(z.object({stage:z.enum(["source","crawler","extraction","semantic_graph","model_understanding","retrieval"]),status:z.enum(["survived","failed","not_tested"]),evidenceIds:z.array(z.string()),note:z.string()})), failedAt:z.string().nullable() });
export const checkSchema = z.object({ id:z.string(), dimension:dimensionIdSchema, label:z.string(), status:z.enum(["pass","fail","na"]), value:z.number().min(0).max(1), weight:z.number().positive(), evidenceIds:z.array(z.string()), limitation:z.string().optional() });
export const metricSchema = z.object({ dimension:dimensionIdSchema.or(z.literal("overall")), score:z.number().min(0).max(100).nullable(), earned:z.number(), denominator:z.number(), applied:z.array(checkSchema), notApplicable:z.array(checkSchema), calculation:z.string(), scoringVersion:z.literal("spectra-v0.1"), limitations:z.array(z.string()) });
export const retrievalSchema = z.object({ id:z.string(), claimId:z.string().optional(), query:z.string(), mode:z.enum(["direct","search_grounded"]), answer:z.string().nullable(), correct:z.boolean().nullable(), evidenceIds:z.array(z.string()), status:z.enum(["passed","failed","not_run","error"]), error:z.string().optional() });
export const issueSchema = z.object({ id:z.string(), type:z.string(), severity:z.enum(["low","medium","high","critical"]), title:z.string(), description:z.string(), affectedEntities:z.array(z.string()), affectedClaims:z.array(z.string()), evidenceIds:z.array(z.string()), likelyCause:z.string(), recommendedFix:z.string(), confidence:z.number().min(0).max(1) });
export const auditSchema = z.object({ id:z.string(), target:z.string().url(), status:z.enum(["idle","validating","crawling","analyzing","evaluating","complete","partial_failure","fatal_failure"]), createdAt:z.string(), completedAt:z.string().nullable(), scoringVersion:z.literal("spectra-v0.1"), crawl:crawlOutputSchema.nullable(), evidence:z.array(evidenceSchema), analysis:siteAnalysisSchema.nullable(), graph:semanticGraphSchema.nullable(), contract:contractSchema.nullable(), survival:z.array(survivalSchema), retrievals:z.array(retrievalSchema), metrics:z.array(metricSchema), issues:z.array(issueSchema), recommendations:z.array(z.object({id:z.string(),issueId:z.string(),whatFailed:z.string(),where:z.string(),evidenceIds:z.array(z.string()),change:z.string(),rationale:z.string()})), modelRuns:z.array(z.object({id:z.string(),provider:z.string(),model:z.string(),purpose:z.string(),status:z.enum(["success","error","skipped"]),durationMs:z.number(),error:z.string().optional()})), warnings:z.array(z.string()) });

export type Audit=z.infer<typeof auditSchema>; export type CrawlOutput=z.infer<typeof crawlOutputSchema>; export type SourceEvidence=z.infer<typeof evidenceSchema>; export type SiteAnalysis=z.infer<typeof siteAnalysisSchema>; export type SemanticGraph=z.infer<typeof semanticGraphSchema>; export type EvaluationContract=z.infer<typeof contractSchema>; export type Check=z.infer<typeof checkSchema>; export type Metric=z.infer<typeof metricSchema>; export type RetrievalResult=z.infer<typeof retrievalSchema>;
