mod extract;mod security;use anyhow::{bail,Context,Result};use extract::Page;use reqwest::{header,Client,redirect::Policy};use serde::Serialize;use std::{collections::{HashMap,HashSet,VecDeque},time::Duration};use url::Url;
const MAX_PAGES:usize=20;const MAX_DEPTH:usize=2;const MAX_BYTES:usize=2*1024*1024;const MAX_REDIRECTS:usize=5;
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct Robots{url:Url,allowed:bool,sitemaps:Vec<Url>,status:Option<u16>}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct Edge{from:Url,to:Url}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct Limits{max_pages:usize,max_depth:usize,max_bytes:usize,timeout_ms:u64,max_redirects:usize}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct Output{target:Url,started_at:String,completed_at:String,robots:Robots,pages:Vec<Page>,crawl_edges:Vec<Edge>,warnings:Vec<String>,limits:Limits}
#[tokio::main]async fn main(){if let Err(e)=run().await{eprintln!("{e:#}");std::process::exit(1)}}
async fn run()->Result<()>{let raw=std::env::args().nth(1).context("usage: spectra-crawler <public-url>")?;let target=security::validate_public_url(&raw).await?;let client=Client::builder().timeout(Duration::from_secs(10)).redirect(Policy::none()).user_agent("SPECTRA/0.1 (+https://github.com/HarshithNayakaL/spectra)").build()?;let robots_url=target.join("/robots.txt")?;let robots=fetch_robots(&client,robots_url).await;let mut queue=VecDeque::from([(target.clone(),0usize)]),seen=HashSet::new(),pages=vec![],edges=vec![],fingerprints=HashMap::new(),warnings=vec![];while let Some((url,depth))=queue.pop_front(){if pages.len()>=MAX_PAGES||!seen.insert(url.as_str().to_owned()){continue}match fetch_page(&client,url.clone()).await{Ok(mut page)=>{if let Some(first)=fingerprints.get(&page.fingerprint){page.duplicate_of=Some(first.clone())}else{fingerprints.insert(page.fingerprint.clone(),page.id.clone());}if depth<MAX_DEPTH{for link in &page.links{if link.domain()==target.domain(){edges.push(Edge{from:url.clone(),to:link.clone()});queue.push_back((link.clone(),depth+1))}}}pages.push(page)},Err(e)=>warnings.push(format!("{}: {}",url,e))}}if pages.is_empty(){bail!("no crawlable HTML pages were retrieved")};let now=timestamp();let output=Output{target,started_at:now.clone(),completed_at:now,robots,pages,crawl_edges:edges,warnings,limits:Limits{max_pages:MAX_PAGES,max_depth:MAX_DEPTH,max_bytes:MAX_BYTES,timeout_ms:10_000,max_redirects:MAX_REDIRECTS}};println!("{}",serde_json::to_string(&output)?);Ok(())}
async fn fetch_page(client:&Client,mut url:Url)->Result<Page>{for _ in 0..=MAX_REDIRECTS{url=security::validate_public_url(url.as_str()).await?;let res=client.get(url.clone()).send().await?;if res.status().is_redirection(){let next=res.headers().get(header::LOCATION).context("redirect has no location")?.to_str()?;url=url.join(next)?;continue}let status=res.status().as_u16();let content_type=res.headers().get(header::CONTENT_TYPE).and_then(|x|x.to_str().ok()).unwrap_or("").to_string();if !content_type.to_ascii_lowercase().contains("text/html"){bail!("unsupported content type {content_type}")}let announced=res.content_length().unwrap_or(0)as usize;if announced>MAX_BYTES{bail!("response exceeds size limit")}let bytes=res.bytes().await?;if bytes.len()>MAX_BYTES{bail!("response exceeds size limit")}return Ok(extract::extract(url,status,content_type,&String::from_utf8_lossy(&bytes)))}bail!("redirect limit exceeded")}
async fn fetch_robots(client:&Client,url:Url)->Robots{match security::validate_public_url(url.as_str()).await.and_then(|_|Ok(())){Err(_)=>Robots{url,allowed:false,sitemaps:vec![],status:None},Ok(_)=>match client.get(url.clone()).send().await{Ok(r)=>{let status=r.status().as_u16();let body=r.text().await.unwrap_or_default();let sitemaps=body.lines().filter_map(|l|l.strip_prefix("Sitemap:").or_else(||l.strip_prefix("sitemap:"))).filter_map(|s|Url::parse(s.trim()).ok()).collect();let denied=body.lines().any(|l|l.trim().eq_ignore_ascii_case("Disallow: /"));Robots{url,allowed:!denied,sitemaps,status:Some(status)}},Err(_)=>Robots{url,allowed:true,sitemaps:vec![],status:None}}}}
fn timestamp()->String{use std::time::{SystemTime,UNIX_EPOCH};SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs().to_string()}

